= PDF via docbookj

An example project that demonstrates how to convert AsciiDoc to PDF through the docbook AsciiDoctor
plugin and then the jdocbook gradle plugin.

Some notes:

* I found little canonical information. There is a lot of trial-and-error here.
* The jdocbook plugin requires stylesheets. They were taken from 
  https://github.com/spring-gradle-plugins/docbook-reference-plugin[the spring "docbook-reference-plugin"].
* The stylesheet requires java-libraries. The two that were needed to build this documentation were
  (xslthl and saxon) were taken from https://github.com/spring-gradle-plugins/docbook-reference-plugin/blob/master/build.gradle.

== Usage

The "normal" usage is through jdocbook, which includes a 'buildDocs' goal; this goal then depends on 'asciidoctor':

 $ ./gradlew buildDocs

For this particual example project, 'buildDocs' is set up to run whenever you run 'asciidoctor' (it uses "buildDocs.finalizedBy asciidoctor" to set this up), so you can also just run the 'asciidoctor' goal:

 $ ./gradlew buildDocs

Open the files _build\docbook\publish\manual\pdf\index.pdf_ to see the output (_build\docbook\publish\reference\pdf\index.pdf_ or _build\docbook\publish\manual\pdf\index.pdf_ also exist, but with placeholder content).
